name 'maestrodev-maven'
version '1.2.0'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-maven'
source 'http://github.com/maestrodev/puppet-maven'
summary 'Apache Maven module for Puppet'
description 'A Puppet module to download artifacts from Maven repositories'
dependency 'maestrodev/wget', '>=1.0.0'
